### ISSUE TITLE
Extract petsc install from CI configuration

### ISSUE THREAD

**Issue by GradedJestRisk** [nennigb/EasterEig#10]
petsc [install](https://github.com/nennigb/EasterEig/blob/master/.github/workflows/ci-ubuntu.yml#L45-L51) takes a few lines and may be stored in an external script

**Comment by nennigb** [comment]
Thank you for your remarks. I understand your point.
Nonetheless, I prefer to group all install steps in the same place for simplicity and for documentation purpose. 
The present script also emphasis that petsc is optional.
In my opinion, adding an install script may confuse people since it will be limited to a single os release.
